version: 2
updates:
  - package-ecosystem:
    directory: "/"
    schedule:
      interval: "daily"
    open-pull-requests-limit: 5
    commit-message:
      prefix: "chore"
    allow:
      - dependency-type: "all"
