name: Build and Deploy Docker Image

on:
  push:
    branches: [main]

env:
  REGISTRY: ${{ secrets.REGISTRY_URL }}
  IMAGE_NAME: ${{ secrets.IMAGE_NAME }}

jobs:
  build:
    runs-on: ubuntu-latest
    outputs:
      image_sha: ${{ steps.set_sha.outputs.sha }}

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Build Docker image and save to tar
        run: |
          docker build --build-arg VITE_API_BASE_URL=${{ secrets.VITE_API_BASE_URL }} -t $REGISTRY/$IMAGE_NAME:${GITHUB_SHA::7} .
          docker save $REGISTRY/$IMAGE_NAME:${GITHUB_SHA::7} -o /tmp/${IMAGE_NAME}_${GITHUB_SHA::7}.tar

      - name: Install doctl
        uses: digitalocean/action-doctl@v2
        with:
          token: ${{ secrets.DIGITALOCEAN_ACCESS_TOKEN }}

      - name: Log in to DigitalOcean Container Registry
        run: doctl registry login --expiry-seconds 600

      - name: Remove all old images
        run: if [ ! -z "$(doctl registry repository list | grep "$(echo $IMAGE_NAME)")" ]; then doctl registry repository delete-manifest $(echo $IMAGE_NAME) $(doctl registry repository list-tags $(echo $IMAGE_NAME) | grep -o "sha.*") --force; else echo "No repository"; fi

      - name: Push image to DigitalOcean Container Registry
        run: docker push $REGISTRY/$IMAGE_NAME:${GITHUB_SHA::7}

      - name: Upload Docker image tarball as artifact
        uses: actions/upload-artifact@v4
        with:
          name: docker-image-${{ github.sha }}
          path: /tmp/${IMAGE_NAME}_${GITHUB_SHA::7}.tar
          retention-days: 7

  deploy:
    needs: build
    runs-on: ubuntu-latest

    steps:
      - name: Deploy Docker image on Droplet
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: ${{ secrets.DROPLET_HOST }}
          username: ${{ secrets.DROPLET_USER }}
          key: ${{ secrets.DROPLET_SSH }}
          script: |
            TAG=${{ github.sha }}
            REGISTRY=${{ secrets.REGISTRY_URL }}
            IMAGE_NAME=${{ secrets.IMAGE_NAME }}
            REGISTRY_EMAIL=${{ secrets.REGISTRY_EMAIL }}
            DO_TOKEN=${{ secrets.DIGITALOCEAN_ACCESS_TOKEN }}

            echo "Logging in to DigitalOcean container registry..."
            echo "$DO_TOKEN" | docker login -u "$REGISTRY_EMAIL" --password-stdin $REGISTRY

            echo "Pulling image: $REGISTRY/$IMAGE_NAME:${TAG:0:7}"
            docker pull $REGISTRY/$IMAGE_NAME:${TAG:0:7}

            echo "Stopping and removing existing container (if any)..."
            docker stop $IMAGE_NAME || true
            docker rm $IMAGE_NAME || true

            echo "Starting new container..."
            docker run -d \
              --restart always \
              --name $IMAGE_NAME \
              -p 4173:4173 \
              $REGISTRY/$IMAGE_NAME:${TAG:0:7}
  
  
