name: Build Docker Image

on:
  pull_request:
    branches: [ main ]
  push:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Extract metadata
        id: meta
        uses: docker/metadata-action@v5
        with:
          images: kpicoder-tracks-fe
          tags: |
            type=ref,event=pr,prefix=pr-
            type=sha,prefix=sha-

      - name: Build Docker image
        uses: docker/build-push-action@v5
        with:
          context: .
          push: false
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}
          cache-from: type=gha
          cache-to: type=gha,mode=max
          outputs: type=docker,dest=/tmp/tracks-client.tar
          platform: linux/amd64
          secrets: |
            VITE_API_BASE_URL=${{ secrets.VITE_API_BASE_URL }}

      - name: Upload Docker image artifact
        uses: actions/upload-artifact@v4
        with:
          name: docker-image-${{ github.sha }}
          path: /tmp/tracks-client.tar
          retention-days: 7

      - name: Display image info
        run: |
          echo "Docker image built successfully!"
          echo "Image tags: ${{ steps.meta.outputs.tags }}"
          echo "Image size:"
          ls -lh /tmp/tracks-client.tar
